### ISSUE TITLE
Editable sets

### ISSUE THREAD

**Issue by johanhenricson** [sureskumar/Looper#29] opened 2018-11-07 13:41 UTC
After Looper has run and created it's groups, it'd be so useful to be able to edit them; tweak the number of copies, rotations, spacings etc.

**Comment by sureskumar** [comment] 2018-11-20 21:08
Great suggestion! Will implement in the next version. Cheers!

**Comment by sureskumar** [comment] 2018-12-27 01:18
Duplicate of #34 Hence closing.

**Closed by sureskumar** 2018-12-27 01:18 UTC
